### ISSUE TITLE
The col/uncol breaks Show instance for R

### ISSUE THREAD

**Issue by nh2** [haskell-numerics/hmatrix#227] opened 2017-05-16 13:12 UTC
The show function for static vectors seems broken if `col` and `uncol` are used:

```haskell
> uncol $ col (1 :: R 1) 
(1.0 :: R 1)
> uncol $ col (1 :: R 2) 
(vector] :: R 2)
> uncol $ col (1 :: R 3) 
(vector,1.0] :: R 3)
> uncol $ col (1 :: R 4) 
(vector,1.0,1.0] :: R 4)
```

There are elements missing / unbalanced parenthesis / stuff is chopped off.

`hmatrix 0.18.0.0`

**Comment by albertoruiz** [comment] 2017-05-17 17:58
Perhaps this is caused by a wrong assumption about the show instance of vectors. With hmatrix 0.18.0.0  and vector-0.10.12.3 I don't have this problem:

    λ> uncol (col (1 :: R 1))
    (1.0 :: R 1)
    λ> uncol (col (1 :: R 2))
    (vector [1.0,1.0] :: R 2)
    λ> uncol (col (1 :: R 4))
    (vector [1.0,1.0,1.0,1.0] :: R 4)

**Comment by nh2** [comment] 2017-05-17 19:14
@albertoruiz Seems possible, I'm on `vector-0.11.0.0`.

**Comment by SamDM** [comment] 2017-08-25 21:14
I can also confirm this on hmatrix-0.18.0.0 (from Stack lts 9.1), no need to call `col` or `uncol`, any vector seems broken:
```
λ: show $ vec4 1 1 1 1
"(vector,1.0,1.0] :: R 4)"
λ: eye :: Sq 4
(diag 0.0 1.0,1.0] :: L 4 4)
```

**Comment by pdobsan** [comment] 2018-02-15 20:22
These problems and also #177 are caused by the change of the show instance of vectors. See https://github.com/haskell/vector/issues/87

The small change below against current master fixes the problem:
```
diff --git a/packages/base/src/Internal/Static.hs b/packages/base/src/Internal/Static.hs
index f9dfff0..9720475 100644
--- a/packages/base/src/Internal/Static.hs
+++ b/packages/base/src/Internal/Static.hs
@@ -321,16 +321,16 @@ isDiagg (Dim (Dim x))
 instance KnownNat n => Show (R n)
   where
     show s@(R (Dim v))
-      | singleV v = "("++show (v!0)++" :: R "++show d++")"
-      | otherwise   = "(vector"++ drop 8 (show v)++" :: R "++show d++")"
+      | singleV v = "(" ++ show (v!0) ++ " :: R " ++ show d ++ ")"
+      | otherwise = "(vector " ++ show v ++ " :: R " ++ show d ++")"
       where
         d = size s
 
 instance KnownNat n => Show (C n)
   where
     show s@(C (Dim v))
-      | singleV v = "("++show (v!0)++" :: C "++show d++")"
-      | otherwise   = "(vector"++ drop 8 (show v)++" :: C "++show d++")"
+      | singleV v = "(" ++ show (v!0) ++ " :: C " ++ show d ++ ")"
+      | otherwise = "(vector " ++ show v ++ " :: C " ++ show d ++")"
       where
         d = size s
```

**Comment by pdobsan** [comment] 2018-04-28 07:32
I have submitted the promised pull request: https://github.com/albertoruiz/hmatrix/pull/270

**Comment by idontgetoutmuch** [comment] 2018-05-20 15:48
Fixed by https://github.com/haskell-numerics/hmatrix/pull/270

**Closed by idontgetoutmuch** 2018-05-20 15:48 UTC
