### ISSUE TITLE
mkSparse drops all-zero rows

### ISSUE THREAD

**Issue by StefanHubner** [haskell-numerics/hmatrix#320] opened 2020-06-07 17:53 UTC
Here is an example: 

Consider the (dense) matrix: 
`fromLists [[1,0],[0,1],[0,0],[1,1],[0,0],[0,0],[1,0],[0,0],[1,0]]`

If I create a sparse matrix using the following `AssocMatrix` representing the above matrix: 
`[((0,0), 1.0), ((1,1), 1.0), ((3,0), 1.0), ((3,1), 1.0), ((6,0), 1.0), ((8,1), 1.0)]`

`mkSparse` evaluates to: 
`SparseR {gmCSR = CSR {csrVals = [1.0,1.0,1.0,1.0,1.0,1.0], csrCols = [1,2,1,2,1,2], csrRows = [1,2,3,5,6,7], csrNRows = 5, csrNCols = 2}, nRows = 5, nCols = 2}`

whereas it should really evaluate to: 
`SparseR (CSR (vector [1.0,1.0,1.0,1.0,1.0,1.0]) ((fromList [1,2,1,2,1,2]) :: Vector CInt) ((fromList [1,2,3,3,5,5,5,6,6,7]) :: Vector CInt) 9 2) 9 2)`

Edit:
Maybe I will fix `mkCSR`, if I have time. In the meantime, I have bodged it by throwing a column vector of zeros into the `AssocMatrix` but, obviously, that's not very clean.

**Comment by HuwCampbell** [comment] 2020-07-02 15:59
Seems to be a duplicate of #220

**Closed** 2020-07-28 09:28 UTC
